# name: build-test 

# on:
#   push: 
#     branches:
#       - main 

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres:11
#         env:
#           POSTGRSES_USER: postgres 
#           POSTGRES_PASSWORD: postgres
#           POSTGRES_DB: postgres
#         ports: ['5432:5432']
#         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
#     steps:
#       - uses: actions/checkout@v2
#       - name: Setup Go 
#         uses: actions/checkout@v2 
#         with: 
#           go-version: '1.17'
#       - name: Install dependencies 
#         run: |
#           go version
#           go install -v 
          
#       - name: Build Binary file 
#         run: go build .
#       - name: Run Tests 
#         env:
#           DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
#           JWT_SECRET: "juls"
#         run: go test -v ./tests/...